#geography_questions.py
question_data = [
    {"question": "Mount Everest is located in the Alps.", "correct_answer": "False"},
    {"question": "The capital of Canada is Toronto.", "correct_answer": "False"},
    {"question": "The Nile is the longest river in the world.", "correct_answer": "True"},
    {"question": "The Amazon rainforest is located in Africa.", "correct_answer": "False"},
    {"question": "The Great Barrier Reef is off the coast of Florida.", "correct_answer": "False"},
    {"question": "Vatican City is the smallest country by land area.", "correct_answer": "True"},
    {"question": "Tokyo is the capital of South Korea.", "correct_answer": "False"},
    {"question": "The Sahara Desert is the largest desert in the world.", "correct_answer": "False"},
    {"question": "The Dead Sea is located between Israel and Jordan.", "correct_answer": "True"},
    {"question": "Iceland is covered in ice.", "correct_answer": "False"},
    {"question": "The currency of Japan is the rupee.", "correct_answer": "False"},
    {"question": "The United Kingdom consists of more than three countries.", "correct_answer": "True"},
    {"question": "The Atlantic Ocean is the biggest ocean on Earth.", "correct_answer": "False"},
    {"question": "New Delhi is the capital of Indonesia.", "correct_answer": "False"},
    {"question": "Sydney is the capital of Australia.", "correct_answer": "False"},
    {"question": "Switzerland has no coastlines.", "correct_answer": "True"},
    {"question": "The Andes mountain range is located in North America.", "correct_answer": "False"},
    {"question": "The Panama Canal connects the Atlantic and Indian Oceans.", "correct_answer": "False"},
    {"question": "Madagascar is the largest island in the world.", "correct_answer": "False"},
    {"question": "Rio de Janeiro is the capital of Brazil.", "correct_answer": "False"},
    {"question": "The equator divides the Earth into the Northern and Southern Hemispheres.", "correct_answer": "True"},
    {"question": "Greenland is the world's largest island.", "correct_answer": "True"},
    {"question": "The capital of Russia is St. Petersburg.", "correct_answer": "False"},
    {"question": "The source of the Amazon River is in Brazil.", "correct_answer": "False"},
    {"question": "Antarctica is the driest continent on Earth.", "correct_answer": "True"},
    {"question": "The Pacific Ocean is larger than Asia.", "correct_answer": "True"},
    {"question": "The Suez Canal connects the Mediterranean Sea to the Red Sea.", "correct_answer": "True"},
    {"question": "The Ural Mountains mark the border between Europe and Asia.", "correct_answer": "True"},
    {"question": "Lake Baikal is the deepest lake in the world.", "correct_answer": "True"},
    {"question": "Asia is the smallest continent by land area.", "correct_answer": "False"},
    {"question": "The Yangtze River is the longest river in Asia.", "correct_answer": "True"},
    {"question": "Mount Kilimanjaro is located in Nepal.", "correct_answer": "False"},
    {"question": "India is part of the European continent.", "correct_answer": "False"},
    {"question": "San Marino is landlocked.", "correct_answer": "True"},
    {"question": "The Tropic of Capricorn is located south of the equator.", "correct_answer": "True"},
    {"question": "Hawaii is the 50th state of the USA.", "correct_answer": "True"},
    {"question": "The longest continental mountain range is the Andes.", "correct_answer": "True"},
    {"question": "The River Thames is located in Paris.", "correct_answer": "False"},
    {"question": "Mount Fuji is an active volcano.", "correct_answer": "True"},
    {"question": "The currency of Brazil is the peso.", "correct_answer": "False"},
    {"question": "Lake Superior is the largest freshwater lake by surface area.", "correct_answer": "True"},
    {"question": "Istanbul spans two continents.", "correct_answer": "True"},
    {"question": "The Philippines is made up of over 500 islands.", "correct_answer": "False"},
    {"question": "The city of Venice stands on about 125 small islands.", "correct_answer": "True"},
    {"question": "The Great Victoria Desert is located in Canada.", "correct_answer": "False"},
    {"question": "The Grand Canyon is around 10 million years old.", "correct_answer": "False"},
    {"question": "Mount Rushmore National Memorial features the heads of four U.S. presidents.", "correct_answer": "True"},
    {"question": "The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea.", "correct_answer": "True"},
    {"question": "The Rocky Mountains are taller and more rugged than the Appalachian Mountains.", "correct_answer": "True"},
    {"question": "The island of Tasmania belongs to New Zealand.", "correct_answer": "False"}
]
