#geography_questions.py
question_data = [
    {"question": "Mount Everest is located in the Alps.", "correct_answer": "False"},
    {"question": "The capital of Canada is Toronto.", "correct_answer": "False"},
    {"question": "The Nile is the longest river in the world.", "correct_answer": "True"},
    {"question": "The Amazon rainforest is located in Africa.", "correct_answer": "False"},
    {"question": "The Great Barrier Reef is off the coast of Florida.", "correct_answer": "False"},
    {"question": "Vatican City is the smallest country by land area.", "correct_answer": "True"},
    {"question": "Tokyo is the capital of South Korea.", "correct_answer": "False"},
    {"question": "The Sahara Desert is the largest hot desert in the world.", "correct_answer": "True"},
    {"question": "The Dead Sea is located between Israel and Jordan.", "correct_answer": "True"},
    {"question": "Iceland is covered in ice.", "correct_answer": "False"},
    {"question": "The currency of Japan is the rupee.", "correct_answer": "False"},
    {"question": "The United Kingdom consists of more than three countries.", "correct_answer": "True"},
    {"question": "The Atlantic Ocean is the biggest ocean on Earth.", "correct_answer": "False"},
    {"question": "New Delhi is the capital of Indonesia.", "correct_answer": "False"},
    {"question": "Sydney is the capital of Australia.", "correct_answer": "False"},
    {"question": "Switzerland has no coastlines.", "correct_answer": "True"},
    {"question": "The Andes mountain range is located in North America.", "correct_answer": "False"},
    {"question": "The Panama Canal connects the Atlantic and Indian Oceans.", "correct_answer": "False"},
    {"question": "Madagascar is the largest island in the world.", "correct_answer": "False"},
    {"question": "Rio de Janeiro is the capital of Brazil.", "correct_answer": "False"},
    {"question": "The equator divides the Earth into the Northern and Southern Hemispheres.", "correct_answer": "True"},
    {"question": "Greenland is the world's largest island.", "correct_answer": "True"},
    {"question": "The capital of Russia is St. Petersburg.", "correct_answer": "False"},
    {"question": "The source of the Amazon River is in Brazil.", "correct_answer": "False"},
    {"question": "Antarctica is the driest continent on Earth.", "correct_answer": "True"},
    {"question": "The Pacific Ocean is larger than Asia.", "correct_answer": "True"},
    {"question": "The Suez Canal connects the Mediterranean Sea to the Red Sea.", "correct_answer": "True"},
    {"question": "The Ural Mountains mark the border between Europe and Asia.", "correct_answer": "True"},
    {"question": "Lake Baikal is the deepest lake in the world.", "correct_answer": "True"},
    {"question": "Asia is the smallest continent by land area.", "correct_answer": "False"},
    {"question": "The Yangtze River is the longest river in Asia.", "correct_answer": "True"},
    {"question": "Mount Kilimanjaro is located in Nepal.", "correct_answer": "False"},
    {"question": "India is part of the European continent.", "correct_answer": "False"},
    {"question": "San Marino is landlocked.", "correct_answer": "True"},
    {"question": "The Tropic of Capricorn is located south of the equator.", "correct_answer": "True"},
    {"question": "Hawaii is the 50th state of the USA.", "correct_answer": "True"},
    {"question": "The longest continental mountain range is the Andes.", "correct_answer": "True"},
    {"question": "The River Thames is located in Paris.", "correct_answer": "False"},
    {"question": "Mount Fuji is an active volcano.", "correct_answer": "True"},
    {"question": "The currency of Brazil is the peso.", "correct_answer": "False"},
    {"question": "Lake Superior is the largest freshwater lake by surface area.", "correct_answer": "True"},
    {"question": "Istanbul spans two continents.", "correct_answer": "True"},
    {"question": "The Philippines is made up of over 7,000 islands.", "correct_answer": "True"},
    {"question": "The city of Venice stands on about 125 small islands.", "correct_answer": "True"},
    {"question": "The Great Victoria Desert is located in Canada.", "correct_answer": "False"},
    {"question": "The Grand Canyon is around 5 to 6 million years old.", "correct_answer": "True"},
    {"question": "Mount Rushmore National Memorial features the heads of four U.S. presidents.", "correct_answer": "True"},
    {"question": "The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea.", "correct_answer": "True"},
    {"question": "The Rocky Mountains are taller and more rugged than the Appalachian Mountains.", "correct_answer": "True"},
    {"question": "The island of Tasmania belongs to New Zealand.", "correct_answer": "False"},
    {"question": "The Great Wall of China can be seen from space with the naked eye.", "correct_answer": "False"},
    {"question": "Bhutan is the only country in the world with a negative carbon footprint.", "correct_answer": "True"},
    {"question": "Mongolia is the most sparsely populated country in the world.", "correct_answer": "True"},
    {"question": "The Gobi Desert is primarily located in India.", "correct_answer": "False"},
    {"question": "Portugal shares a border with only one other country.", "correct_answer": "True"},
    {"question": "The Caspian Sea is the world's largest saltwater lake.", "correct_answer": "True"},
    {"question": "The city of Dubai is the capital of the United Arab Emirates.", "correct_answer": "False"},
    {"question": "The Serengeti National Park is located in South Africa.", "correct_answer": "False"},
    {"question": "The island of Borneo is shared by three countries.", "correct_answer": "True"},
    {"question": "The city of Timbuktu is located in Mali.", "correct_answer": "True"},
    {"question": "The highest waterfall in the world, Angel Falls, is located in Venezuela.", "correct_answer": "True"},
    {"question": "The Maldives is the lowest country in the world in terms of average ground level.", "correct_answer": "True"},
    {"question": "The Danube River flows through 10 countries, more than any other river in the world.", "correct_answer": "True"},
    {"question": "The city of Bangkok is also known as the 'City of Angels'.", "correct_answer": "True"},
    {"question": "Australia is both a country and a continent.", "correct_answer": "True"},
    {"question": "The English Channel separates England from France.", "correct_answer": "True"},
    {"question": "The highest mountain in Africa is Mount Kenya.", "correct_answer": "False"},
    {"question": "There are five countries with land within the Arctic Circle.", "correct_answer": "False"},
    {"question": "The Karakoram Highway is the world's highest paved international road, connecting China and Pakistan.", "correct_answer": "True"},
    {"question": "The city of Johannesburg is also known as the 'City of Gold' due to its gold-mining heritage.", "correct_answer": "True"},
    {"question": "The Trans-Siberian Railway, the longest railway line in the world, connects Moscow to Vladivostok.", "correct_answer": "True"},
    {"question": "The Sahara Desert stretches across several countries in North Africa.", "correct_answer": "True"},
    {"question": "The Galápagos Islands are part of the territory of Ecuador.", "correct_answer": "True"},
    {"question": "Lake Titicaca, the world's highest navigable lake, is situated between Peru and Bolivia.", "correct_answer": "True"},
    {"question": "The city of Las Vegas is known as the 'Wind City'.", "correct_answer": "False"},
    {"question": "The Panama Canal was originally built by the French.", "correct_answer": "True"},
    {"question": "The Alps mountain range stretches across eight European countries.", "correct_answer": "True"},
    {"question": "The currency of Switzerland is the Euro.", "correct_answer": "False"},
    {"question": "The Tropic of Cancer passes through Mexico.", "correct_answer": "True"},
    {"question": "The Dead Sea is the saltiest sea in the world.", "correct_answer": "True"},
    {"question": "The longest river in Europe is the Volga.", "correct_answer": "True"},
    {"question": "The currency of Sweden is the Euro.", "correct_answer": "False"},
    {"question": "The Great Victoria Desert is the largest desert in Australia.", "correct_answer": "True"},
    {"question": "The River Danube empties into the Black Sea.", "correct_answer": "True"},
    {"question": "The highest capital city in the world is Quito.", "correct_answer": "True"},
    {"question": "Vancouver is the capital city of British Columbia, Canada.", "correct_answer": "False"},
    {"question": "The island nation of Fiji is located in the Atlantic Ocean.", "correct_answer": "False"},
    {"question": "The city of Brussels is the de facto capital of the European Union.", "correct_answer": "True"},
    {"question": "Bali is an island province of Indonesia.", "correct_answer": "True"},
    {"question": "The country with the most number of islands is Sweden.", "correct_answer": "True"},
    {"question": "The Hoover Dam is located on the Colorado River.", "correct_answer": "True"},
    {"question": "The Kalahari Desert is located in South America.", "correct_answer": "False"},
    {"question": "Machu Picchu is an ancient city built by the Aztec civilization.", "correct_answer": "False"},
    {"question": "The largest desert in the world is the Sahara.", "correct_answer": "False"},
    {"question": "The Louvre Museum is located in London.", "correct_answer": "False"},
    {"question": "The Great Pyramids are located in the city of Luxor.", "correct_answer": "False"},
    {"question": "The Amazon River discharges more water than any other river in the world.", "correct_answer": "True"},
    {"question": "The Taj Mahal is located in the city of Mumbai.", "correct_answer": "False"},
    {"question": "The Caribbean island of Trinidad is located off the coast of Venezuela.", "correct_answer": "True"},
    {"question": "The river Seine flows through the city of Rome.", "correct_answer": "False"},
    {"question": "Mount Elbrus is the highest mountain in Europe.", "correct_answer": "True"},
    {"question": "The city of Vienna is located on the banks of the River Danube.", "correct_answer": "True"},
    {"question": "The currency used in Argentina is the peso.", "correct_answer": "True"},
    {"question": "The official languages of Singapore include English, Malay, Mandarin, and Tamil.", "correct_answer": "True"},
    {"question": "The country of Belize is located in South America.", "correct_answer": "False"},
    {"question": "The Channel Tunnel connects England and Ireland.", "correct_answer": "False"},
    {"question": "Lake Ontario is one of the Great Lakes of North America.", "correct_answer": "True"},
    {"question": "The country known as the 'Land of the Rising Sun' is Japan.", "correct_answer": "True"},
    {"question": "The river that runs through Egypt is the Euphrates.", "correct_answer": "False"},
    {"question": "K2, the second-highest mountain in the world, is part of the Himalayas.", "correct_answer": "False"},
    {"question": "The capital city of Spain is Barcelona.", "correct_answer": "False"},
    {"question": "The city of Monaco is the capital of the country Monaco.", "correct_answer": "True"},
    {"question": "The original name of the city of Bangkok is the longest city name in the world.", "correct_answer": "True"},
    {"question": "The country with the most official languages is South Africa.", "correct_answer": "True"},
    {"question": "The smallest ocean in the world is the Indian Ocean.", "correct_answer": "False"},
    {"question": "The state of Alaska is the westernmost and easternmost state of the United States.", "correct_answer": "True"},
    {"question": "The Great Lakes border both the United States and Mexico.", "correct_answer": "False"},
    {"question": "The city of Ulaanbaatar is the capital of Mongolia.", "correct_answer": "True"},
    {"question": "The official language of Brazil is Spanish.", "correct_answer": "False"},
    {"question": "The Rhine River flows through six countries.", "correct_answer": "True"},
    {"question": "The capital of Morocco is Marrakesh.", "correct_answer": "False"},
    {"question": "The Gulf of Mexico is the largest gulf in the world.", "correct_answer": "True"},
    {"question": "The Andes Mountains are the longest mountain range in the world.", "correct_answer": "True"},
    {"question": "The river Jordan flows into the Black Sea.", "correct_answer": "False"},
    {"question": "The Caspian Sea is the largest lake by surface area in the world.", "correct_answer": "True"}
]