#history_questions.py
question_data = [
    {"question": "World War I began in 1914.", "correct_answer": "True"},
    {"question": "The Roman Empire was established in 27 AD.", "correct_answer": "True"},
    {"question": "The Great Wall of China was built to fend off Viking invaders.", "correct_answer": "False"},
    {"question": "Napoleon Bonaparte was a prominent general during the French Revolution.", "correct_answer": "True"},
    {"question": "The Titanic sank in 1912.", "correct_answer": "True"},
    {"question": "Mahatma Gandhi led the salt march in 1930 to protest British salt taxes.", "correct_answer": "True"},
    {"question": "The Battle of Hastings took place in 1066.", "correct_answer": "True"},
    {"question": "The Aztec civilization was located in modern-day Peru.", "correct_answer": "False"},
    {"question": "The Declaration of Independence was signed in 1775.", "correct_answer": "False"},
    {"question": "The Renaissance began in the 14th century.", "correct_answer": "True"},
    {"question": "Albert Einstein was awarded the Nobel Prize in Physics for his theory of relativity.", "correct_answer": "False"},
    {"question": "The Mongol Empire was the largest contiguous empire in history.", "correct_answer": "True"},
    {"question": "The Cuban Missile Crisis occurred in the 1970s.", "correct_answer": "False"},
    {"question": "Cleopatra was an ancient Egyptian queen.", "correct_answer": "True"},
    {"question": "Martin Luther King Jr. delivered his famous 'I have a dream' speech in 1963.", "correct_answer": "True"},
    {"question": "Joan of Arc was executed for being accused of witchcraft.", "correct_answer": "True"},
    {"question": "The city of Pompeii was destroyed by a volcano in 79 A.D.", "correct_answer": "True"},
    {"question": "The first World Cup took place in 1930.", "correct_answer": "True"},
    {"question": "The ancient city of Troy was located in modern-day Greece.", "correct_answer": "False"},
    {"question": "Genghis Khan was the founder of the Ottoman Empire.", "correct_answer": "False"},
    {"question": "The Hundred Years' War lasted 116 years.", "correct_answer": "False"},
    {"question": "Marco Polo traveled from Italy to China in the 13th century.", "correct_answer": "True"},
    {"question": "The Magna Carta was signed in 1215.", "correct_answer": "True"},
    {"question": "Alexander the Great was a famous king of Sparta.", "correct_answer": "False"},
    {"question": "The American Civil War began in 1861.", "correct_answer": "True"},
    {"question": "Christopher Columbus discovered America in 1492.", "correct_answer": "True"},
    {"question": "The Soviet Union dissolved in 1991.", "correct_answer": "True"},
    {"question": "The Wright brothers made their first powered flight in 1905.", "correct_answer": "False"},
    {"question": "The Berlin Wall fell in 1989.", "correct_answer": "True"},
    {"question": "The assassination of Archduke Franz Ferdinand was a direct cause of World War II.", "correct_answer": "False"},
    {"question": "The French Revolution began in 1789.", "correct_answer": "True"},
    {"question": "The atomic bombings of Hiroshima and Nagasaki took place in 1946.", "correct_answer": "False"},
    {"question": "Julius Caesar was assassinated in 44 B.C.", "correct_answer": "True"},
    {"question": "The Industrial Revolution began in the 18th century.", "correct_answer": "True"},
    {"question": "The Suez Canal connects the Mediterranean Sea to the Red Sea.", "correct_answer": "True"},
    {"question": "Queen Victoria was the monarch of France during the Victorian era.", "correct_answer": "False"},
    {"question": "The U.S. purchased Alaska from Canada.", "correct_answer": "False"},
    {"question": "The first Olympic Games were held in Athens in 1896.", "correct_answer": "True"},
    {"question": "The Roman Colosseum could hold up to 80,000 spectators.", "correct_answer": "True"},
    {"question": "Vikings were seafaring people from the late eighth to early 11th century.", "correct_answer": "True"},
    {"question": "The currency in use during ancient Rome was called Drachma.", "correct_answer": "False"},
    {"question": "The Code of Hammurabi is one of the oldest deciphered writings of significant length in the world.", "correct_answer": "True"},
    {"question": "The ancient civilization of Sumer was located in modern-day Iran.", "correct_answer": "False"},
    {"question": "The Boston Tea Party took place in 1773.", "correct_answer": "True"},
    {"question": "The Byzantine Empire was centered around the city of Rome.", "correct_answer": "False"},
    {"question": "The Great Depression began in 1929.", "correct_answer": "True"},
    {"question": "The Battle of Waterloo marked the end of the French Revolution.", "correct_answer": "False"},
    {"question": "The ancient Egyptians worshiped a sun god named Ra.", "correct_answer": "True"},
    {"question": "The phrase 'Let them eat cake' is often attributed to Marie Antoinette.", "correct_answer": "True"},
    {"question": "The pyramids of Giza were built as tombs for pharaohs.", "correct_answer": "True"},
]
