#math_questions.py
question_data = [
    {"question": "The square root of 144 is 12.", "correct_answer": "True"},
    {"question": "In Roman numerals, X represents the number 5.", "correct_answer": "False"},
    {"question": "The number 0 is considered an even number.", "correct_answer": "True"},
    {"question": "Pi (\( \pi \)) can be accurately represented as a fraction.", "correct_answer": "False"},
    {"question": "The sum of the angles of a triangle always equals 180 degrees.", "correct_answer": "True"},
    {"question": "The number 'one billion' has 9 zeros.", "correct_answer": "True"},
    {"question": "A heptagon has 8 sides.", "correct_answer": "False"},
    {"question": "The factorial of 0 is 1.", "correct_answer": "True"},
    {"question": "In geometry, a 'plane' has a surface with zero thickness.", "correct_answer": "True"},
    {"question": "The number 'eleven' is a prime number.", "correct_answer": "True"},
    {"question": "There are 100 centimeters in a meter.", "correct_answer": "True"},
    {"question": "A 'polygon' is a three-sided shape.", "correct_answer": "False"},
    {"question": "The number 2 is the only even prime number.", "correct_answer": "True"},
    {"question": "The Fibonacci sequence starts with the numbers 1, 2.", "correct_answer": "False"},
    {"question": "A right triangle can never be equilateral.", "correct_answer": "True"},
    {"question": "A 'decagon' has 10 sides.", "correct_answer": "True"},
    {"question": "The number 'i' represents an imaginary unit in mathematics.", "correct_answer": "True"},
    {"question": "In mathematics, 'Euler's number' is represented by the letter \( e \).", "correct_answer": "True"},
    {"question": "A 'chord' in a circle is a line that connects two points on the circle's circumference.", "correct_answer": "True"},
    {"question": "In mathematics, the 'commutative property' refers to the order of operations.", "correct_answer": "False"},
    {"question": "The number 5 is a composite number.", "correct_answer": "False"},
    {"question": "The product of any number and zero is always zero.", "correct_answer": "True"},
    {"question": "A parallelogram has opposite sides of equal length.", "correct_answer": "True"},
    {"question": "The formula to calculate the area of a circle is \( \pi r^2 \).", "correct_answer": "True"},
    {"question": "A hexagon has 5 sides.", "correct_answer": "False"},
    {"question": "The number 1 is neither prime nor composite.", "correct_answer": "True"},
    {"question": "The 'Pythagorean theorem' applies to right triangles.", "correct_answer": "True"},
    {"question": "The number 9 is a prime number.", "correct_answer": "False"},
    {"question": "An isosceles triangle has three sides of equal length.", "correct_answer": "False"},
    {"question": "In statistics, the 'median' refers to the most frequently occurring number.", "correct_answer": "False"},
    {"question": "A 'quadrilateral' is a four-sided polygon.", "correct_answer": "True"},
    {"question": "In base-10, the number 10^3 equals 1000.", "correct_answer": "True"},
    {"question": "In geometry, two lines that never meet are called 'perpendicular'.", "correct_answer": "False"},
    {"question": "The number \( \sqrt{-1} \) is considered a real number.", "correct_answer": "False"},
    {"question": "The sum of two odd numbers is always even.", "correct_answer": "True"},
    {"question": "A 'rhombus' is a type of rectangle.", "correct_answer": "False"},
    {"question": "There are 360 degrees in a circle.", "correct_answer": "True"},
    {"question": "In Roman numerals, the letter 'L' stands for 100.", "correct_answer": "False"},
    {"question": "The smallest two-digit prime number is 11.", "correct_answer": "True"},
    {"question": "The number 57 is a prime number.", "correct_answer": "False"},
    {"question": "A 'radius' of a circle connects the center of the circle to a point on its circumference.", "correct_answer": "True"},
    {"question": "The 'distributive property' states that \( a(b + c) = ab + ac \).", "correct_answer": "True"},
    {"question": "In trigonometry, the 'sine' of an angle in a right triangle is the ratio of the opposite side to the hypotenuse.", "correct_answer": "True"},
    {"question": "A 'cube' has 8 faces.", "correct_answer": "False"},
    {"question": "An 'octagon' has 8 sides.", "correct_answer": "True"},
    {"question": "The number 'seven' is a prime number.", "correct_answer": "True"},
    {"question": "The sum of the angles in a quadrilateral is 360 degrees.", "correct_answer": "True"},
    {"question": "The 'associative property' states that the way numbers are grouped in an addition or multiplication does not affect their sum or product.", "correct_answer": "True"},
    {"question": "In algebra, a 'coefficient' is a number used to multiply a variable.", "correct_answer": "True"},
    {"question": "The number 'seventeen' is a composite number.", "correct_answer": "False"}
]
