#math_questions.py
question_data = [
    {"question": "The square root of 144 is 12.", "correct_answer": "True"},
    {"question": "In Roman numerals, X represents the number 5.", "correct_answer": "False"},
    {"question": "The number 0 is considered an even number.", "correct_answer": "True"},
    {"question": "Pi (\( \pi \)) can be accurately represented as a fraction.", "correct_answer": "False"},
    {"question": "The sum of the angles of a triangle always equals 180 degrees.", "correct_answer": "True"},
    {"question": "The number 'one billion' has 9 zeros.", "correct_answer": "True"},
    {"question": "A heptagon has 8 sides.", "correct_answer": "False"},
    {"question": "The factorial of 0 is 1.", "correct_answer": "True"},
    {"question": "In geometry, a 'plane' has a surface with zero thickness.", "correct_answer": "True"},
    {"question": "The number 'eleven' is a prime number.", "correct_answer": "True"},
    {"question": "There are 100 centimeters in a meter.", "correct_answer": "True"},
    {"question": "A 'polygon' is a three-sided shape.", "correct_answer": "False"},
    {"question": "The number 2 is the only even prime number.", "correct_answer": "True"},
    {"question": "The Fibonacci sequence starts with the numbers 1, 2.", "correct_answer": "False"},
    {"question": "A right triangle can never be equilateral.", "correct_answer": "True"},
    {"question": "A 'decagon' has 10 sides.", "correct_answer": "True"},
    {"question": "The number 'i' represents an imaginary unit in mathematics.", "correct_answer": "True"},
    {"question": "In mathematics, 'Euler's number' is represented by the letter \( e \).", "correct_answer": "True"},
    {"question": "A 'chord' in a circle is a line that connects two points on the circle's circumference.", "correct_answer": "True"},
    {"question": "In mathematics, the 'commutative property' refers to the order of operations.", "correct_answer": "False"},
    {"question": "The number 5 is a composite number.", "correct_answer": "False"},
    {"question": "The product of any number and zero is always zero.", "correct_answer": "True"},
    {"question": "A parallelogram has opposite sides of equal length.", "correct_answer": "True"},
    {"question": "The formula to calculate the area of a circle is \( \pi r^2 \).", "correct_answer": "True"},
    {"question": "A hexagon has 5 sides.", "correct_answer": "False"},
    {"question": "The number 1 is neither prime nor composite.", "correct_answer": "True"},
    {"question": "The 'Pythagorean theorem' applies to right triangles.", "correct_answer": "True"},
    {"question": "The number 9 is a prime number.", "correct_answer": "False"},
    {"question": "An isosceles triangle has three sides of equal length.", "correct_answer": "False"},
    {"question": "In statistics, the 'median' refers to the most frequently occurring number.", "correct_answer": "False"},
    {"question": "A 'quadrilateral' is a four-sided polygon.", "correct_answer": "True"},
    {"question": "In base-10, the number 10^3 equals 1000.", "correct_answer": "True"},
    {"question": "In geometry, two lines that never meet are called 'perpendicular'.", "correct_answer": "False"},
    {"question": "The number \( \sqrt{-1} \) is considered a real number.", "correct_answer": "False"},
    {"question": "The sum of two odd numbers is always even.", "correct_answer": "True"},
    {"question": "A 'rhombus' is a type of rectangle.", "correct_answer": "False"},
    {"question": "There are 360 degrees in a circle.", "correct_answer": "True"},
    {"question": "In Roman numerals, the letter 'L' stands for 100.", "correct_answer": "False"},
    {"question": "The smallest two-digit prime number is 11.", "correct_answer": "True"},
    {"question": "The number 57 is a prime number.", "correct_answer": "False"},
    {"question": "A 'radius' of a circle connects the center of the circle to a point on its circumference.", "correct_answer": "True"},
    {"question": "The 'distributive property' states that \( a(b + c) = ab + ac \).", "correct_answer": "True"},
    {"question": "In trigonometry, the 'sine' of an angle in a right triangle is the ratio of the opposite side to the hypotenuse.", "correct_answer": "True"},
    {"question": "A 'cube' has 8 faces.", "correct_answer": "False"},
    {"question": "An 'octagon' has 8 sides.", "correct_answer": "True"},
    {"question": "The number 'seven' is a prime number.", "correct_answer": "True"},
    {"question": "The sum of the angles in a quadrilateral is 360 degrees.", "correct_answer": "True"},
    {"question": "The 'associative property' states that the way numbers are grouped in an addition or multiplication does not affect their sum or product.", "correct_answer": "True"},
    {"question": "In algebra, a 'coefficient' is a number used to multiply a variable.", "correct_answer": "True"},
    {"question": "The number 'seventeen' is a composite number.", "correct_answer": "False"},
    {"question": "The symbol for 'not equal to' in mathematics is \( \neq \).", "correct_answer": "True"},
    {"question": "A polygon with all sides and angles equal is called 'regular'.", "correct_answer": "True"},
    {"question": "In a right triangle, the side opposite the right angle is called the 'adjacent'.", "correct_answer": "False"},
    {"question": "The formula for the perimeter of a rectangle is \( P = 2l + 2w \).", "correct_answer": "True"},
    {"question": "A 'pentagon' has 6 sides.", "correct_answer": "False"},
    {"question": "In mathematics, 'absolute value' represents the distance of a number from zero.", "correct_answer": "True"},
    {"question": "The 'natural numbers' include zero.", "correct_answer": "False"},
    {"question": "The term 'integer' represents both whole numbers and their negative counterparts.", "correct_answer": "True"},
    {"question": "In geometry, a 'secant' is a line that touches a circle at one point only.", "correct_answer": "False"},
    {"question": "The 'golden ratio' is approximately equal to 1.618.", "correct_answer": "True"},
    {"question": "A 'prime factor' of a number is a factor that is prime.", "correct_answer": "True"},
    {"question": "A 'composite number' has more than two distinct positive divisors.", "correct_answer": "True"},
    {"question": "The number \( \pi \) (Pi) is a rational number.", "correct_answer": "False"},
    {"question": "The number 0.333... is equal to \( \frac{1}{3} \).", "correct_answer": "True"},
    {"question": "In probability, an event that cannot happen has a probability of 1.", "correct_answer": "False"},
    {"question": "In algebra, 'binomial' means an expression with three terms.", "correct_answer": "False"},
    {"question": "The 'mean' of a set of numbers is their average.", "correct_answer": "True"},
    {"question": "The mathematical constant \( e \) is approximately 2.718.", "correct_answer": "True"},
    {"question": "A line which divides a circle into two equal parts is called a 'radius'.", "correct_answer": "False"},
    {"question": "In statistics, 'mode' refers to the value that appears most frequently in a data set.", "correct_answer": "True"},
    {"question": "The 'range' of a set of numbers is the difference between the highest and lowest numbers in the set.", "correct_answer": "True"},
    {"question": "An angle that measures exactly 90 degrees is called an 'obtuse' angle.", "correct_answer": "False"},
    {"question": "The number 0.101001000100001... is called a 'Liouville number'.", "correct_answer": "True"},
    {"question": "In geometry, 'congruent' means having the same size and shape.", "correct_answer": "True"},
    {"question": "A 'conic section' can be a circle, ellipse, parabola, or hyperbola.", "correct_answer": "True"},
    {"question": "The 'product' of two numbers is the result of adding them together.", "correct_answer": "False"},
    {"question": "A 'factorial' of a number is the product of all whole numbers from 1 to that number.", "correct_answer": "True"},
    {"question": "In mathematics, a 'matrix' is a rectangular array of numbers.", "correct_answer": "True"},
    {"question": "A triangle with one angle measuring more than 90 degrees is called 'acute'.", "correct_answer": "False"},
    {"question": "The set of all x-values in a function is called the 'domain'.", "correct_answer": "True"},
    {"question": "In mathematics, 'logarithms' are the inverses of exponentials.", "correct_answer": "True"},
    {"question": "A 'square number' is the product of an integer multiplied by itself.", "correct_answer": "True"},
    {"question": "The number 1 is the multiplicative identity.", "correct_answer": "True"},
    {"question": "The highest power of x in a polynomial is called its 'degree'.", "correct_answer": "True"},
    {"question": "In geometry, two lines that never meet are called 'parallel'.", "correct_answer": "True"},
    {"question": "The equation \( ax^2 + bx + c = 0 \) is known as a quadratic equation.", "correct_answer": "True"},
    {"question": "The 'hypotenuse' is the longest side in a right triangle.", "correct_answer": "True"},
    {"question": "Two angles that add up to 180 degrees are called complementary.", "correct_answer": "False"},
    {"question": "A polygon with 7 sides is called a heptagon.", "correct_answer": "True"},
    {"question": "The number 10 is a prime number.", "correct_answer": "False"},
    {"question": "A line segment joining two points on a circle and passing through its center is called a diameter.", "correct_answer": "True"},
    {"question": "The sum of probabilities in a probability space is always 2.", "correct_answer": "False"},
    {"question": "The number 22/7 is a rational approximation of \( \pi \).", "correct_answer": "True"},
    {"question": "A set that contains all of its limit points is called a closed set.", "correct_answer": "True"},
    {"question": "The number \( \sqrt[3]{-8} \) is imaginary.", "correct_answer": "False"},
    {"question": "The highest common factor (HCF) of two numbers also divides their sum.", "correct_answer": "True"},
    {"question": "A rhombus always has four right angles.", "correct_answer": "False"},
    {"question": "The sum of exterior angles of a polygon always equals 360 degrees.", "correct_answer": "True"},
    {"question": "The formula for the volume of a cylinder is \( \pi r^2 h \).", "correct_answer": "True"},
    {"question": "An equilateral triangle is always isosceles.", "correct_answer": "True"},
    {"question": "The base 10 logarithm of 1000 is 4.", "correct_answer": "False"},
    {"question": "In a standard deck of cards, the probability of drawing an Ace is \( \frac{1}{13} \).", "correct_answer": "True"},
    {"question": "The sine of 45 degrees is \( \frac{1}{\sqrt{2}} \).", "correct_answer": "True"},
    {"question": "A set with no elements is called a null set.", "correct_answer": "True"},
    {"question": "In mathematics, a group of symbols representing a number is called a numeral.", "correct_answer": "True"},
    {"question": "The number -5 is greater than -7.", "correct_answer": "True"},
    {"question": "The area of a circle can be calculated using the formula \( 2\pi r \).", "correct_answer": "False"},
    {"question": "In an isosceles triangle, at least two sides are of equal length.", "correct_answer": "True"},
    {"question": "An octahedron has 8 faces.", "correct_answer": "True"},
    {"question": "The common logarithm uses base 2.", "correct_answer": "False"},
    {"question": "The term 'irrational number' refers to a number that cannot be expressed as a fraction.", "correct_answer": "True"},
    {"question": "The symbol \( \in \) is used to denote membership in a set.", "correct_answer": "True"},
    {"question": "The square root of 64 is 6.", "correct_answer": "False"},
    {"question": "A triangle cannot have more than one right angle.", "correct_answer": "True"},
    {"question": "The sum of the probabilities of all possible outcomes in an experiment is 1.", "correct_answer": "True"},
    {"question": "A polygon with all interior angles less than 180 degrees is called concave.", "correct_answer": "False"},
    {"question": "The number of degrees in a straight angle is 180.", "correct_answer": "True"},
    {"question": "If two lines are perpendicular to the same line, then they are parallel to each other.", "correct_answer": "True"},
    {"question": "A scalene triangle has all three sides of different lengths.", "correct_answer": "True"},
    {"question": "The number of sides in a nonagon is 9.", "correct_answer": "True"},
    {"question": "A number raised to the power of zero is always 1.", "correct_answer": "True"},
    {"question": "The number of degrees in a complete circle is 400.", "correct_answer": "False"}
]