#movies_and_tv_show_questions.py
question_data = [

    {"question": "Bryan Cranston played the role of Walter White in 'Breaking Bad'.", "correct_answer": "True"},
    {"question": "The TV show 'Stranger Things' is set in the 1980s.", "correct_answer": "True"},
    {"question": "The movie 'Jurassic Park' was directed by Steven Spielberg.", "correct_answer": "True"},
    {"question": "'The Lord of the Rings' was originally a book written by J.R.R. Tolkien.", "correct_answer": "True"},
    {"question": "'The Mandalorian' is a spin-off series from 'Star Wars'.", "correct_answer": "True"},
    {"question": "The character named Jack Sparrow is from the movie series 'Pirates of the Caribbean'.", "correct_answer": "True"},
    {"question": "'The Witcher' is a TV series based on a video game.", "correct_answer": "True"},
    {"question": "In 'Harry Potter', the character who says, 'After all this time? Always.' is Severus Snape.", "correct_answer": "True"},
    {"question": "'Guardians of the Galaxy' is part of the Marvel Cinematic Universe.", "correct_answer": "True"},
    {"question": "'The Crown' is a Netflix series about the reign of Queen Elizabeth II.", "correct_answer": "True"},
    {"question": "Heath Ledger won a posthumous Academy Award for his role as the Joker in 'The Dark Knight'.", "correct_answer": "True"},
    {"question": "The movie 'Inception' deals with the concept of entering people's dreams.", "correct_answer": "True"},
    {"question": "'Mad Max: Fury Road' was released in the 1990s.", "correct_answer": "False"},
    {"question": "The sitcom 'The Big Bang Theory' revolves around a group of friends living in New York.", "correct_answer": "False"},
    {"question": "In 'Star Wars', the character who famously says 'I've got a bad feeling about this' in every episode is Han Solo.", "correct_answer": "False"},
    {"question": "The TV show 'F.R.I.E.N.D.S' had 12 seasons.", "correct_answer": "False"},
    {"question": "'Frozen' is a movie produced by DreamWorks.", "correct_answer": "False"},
    {"question": "'Westworld' is a TV series based on a novel written by Michael Crichton.", "correct_answer": "True"},
    {"question": "'Wakanda' is the fictional African nation in 'The Lion King'.", "correct_answer": "False"},
    {"question": "'Scarface' is a movie about a gangster in the 1920s during the prohibition era.", "correct_answer": "False"},
    {"question": "'The Office' is a mockumentary sitcom that depicts the everyday work lives of office employees.", "correct_answer": "True"},
    {"question": "'Avatar: The Last Airbender' is a TV series that aired on HBO.", "correct_answer": "False"},
    {"question": "'Grey's Anatomy' is a medical drama TV series.", "correct_answer": "True"},
    {"question": "'The Godfather' is a movie directed by Quentin Tarantino.", "correct_answer": "False"},
    {"question": "The movie 'Titanic' was released in 1999.", "correct_answer": "False"},
    {"question": "'Pulp Fiction' is known for its chronological story-telling.", "correct_answer": "False"},
    {"question": "'Chernobyl' is a historical drama TV series that revolves around the nuclear disaster of 1986.", "correct_answer": "True"},
    {"question": "The movie 'Toy Story' was produced by Pixar Animation Studios.", "correct_answer": "True"},
    {"question": "The movie 'La La Land' won the Academy Award for Best Picture in 2017.", "correct_answer": "False"},
    {"question": "Anthony Hopkins played the character of Hannibal Lecter in 'The Silence of the Lambs'.", "correct_answer": "True"},
    {"question": "The 'Rocky' film series primarily focuses on boxing.", "correct_answer": "True"},
    {"question": "'Django Unchained' is set during the times of the American Civil War.", "correct_answer": "True"},
    {"question": "The TV series 'Peaky Blinders' is set during the early 1900s in Birmingham, England.", "correct_answer": "True"},
    {"question": "'Parasite' is a South Korean black comedy thriller film directed by Bong Joon-ho.", "correct_answer": "True"},
    {"question": "In 'The Matrix', the main protagonist's hacker alias is Neo.", "correct_answer": "True"},
    {"question": "'Iron Man' was the first movie released in the Marvel Cinematic Universe.", "correct_answer": "True"},
    {"question": "The movie 'The Shawshank Redemption' is based on a novel written by Stephen King.", "correct_answer": "True"},
    {"question": "'Narcos' is a TV series that chronicles the life of drug lord Pablo Escobar.", "correct_answer": "True"},
    {"question": "In 'Game of Thrones', Daenerys Targaryen has two dragons.", "correct_answer": "False"},
    {"question": "'Black Mirror' is a TV series that explores a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.", "correct_answer": "True"},
    {"question": "'Breaking Bad' is a TV series that chronicles the life of a high school chemistry teacher turned methamphetamine manufacturer.", "correct_answer": "True"},
    {"question": "The movie 'A Beautiful Mind' is based on the life of mathematician John Nash.", "correct_answer": "True"},
    {"question": "The 'Harry Potter' film series consists of 8 movies.", "correct_answer": "True"},
    {"question": "'The Walking Dead' is a TV series that revolves around a group of survivors in a post-apocalyptic world filled with zombies.", "correct_answer": "True"},
    {"question": "The movie 'Forrest Gump' chronicles the life of a man with low intelligence and his adventures through the late 20th century.", "correct_answer": "True"},
    {"question": "In 'The Simpsons', the head of the Simpson family is named Homer.", "correct_answer": "True"},
    {"question": "'BoJack Horseman' is an animated TV series that revolves around a washed-up actor who is a horse and his struggles with addiction, self-worth, and relationships.", "correct_answer": "True"},
    {"question": "'Better Call Saul' is a prequel to 'Breaking Bad'.", "correct_answer": "True"},
    {"question": "The movie 'The Wolf of Wall Street' is based on the life of stockbroker Jordan Belfort.", "correct_answer": "True"},
    {"question": "The TV series 'Vikings' chronicles the legendary Norse hero Ragnar Lothbrok's journey as a legendary Norse hero and legendary king of Denmark.", "correct_answer": "True"},
]
