#movies_and_tv_show_questions.py
question_data = [
    {"question": "Bryan Cranston played the role of Walter White in 'Breaking Bad'.", "correct_answer": "True"},
    {"question": "The TV show 'Stranger Things' is set in the 1980s.", "correct_answer": "True"},
    {"question": "The movie 'Jurassic Park' was directed by Steven Spielberg.", "correct_answer": "True"},
    {"question": "'The Lord of the Rings' was originally a book written by J.R.R. Tolkien.", "correct_answer": "True"},
    {"question": "'The Mandalorian' is a spin-off series from 'Star Wars'.", "correct_answer": "True"},
    {"question": "The character named Jack Sparrow is from the movie series 'Pirates of the Caribbean'.", "correct_answer": "True"},
    {"question": "'The Witcher' is a TV series based on a video game.", "correct_answer": "True"},
    {"question": "In 'Harry Potter', the character who says, 'After all this time? Always.' is Severus Snape.", "correct_answer": "True"},
    {"question": "'Guardians of the Galaxy' is part of the Marvel Cinematic Universe.", "correct_answer": "True"},
    {"question": "'The Crown' is a Netflix series about the reign of Queen Elizabeth II.", "correct_answer": "True"},
    {"question": "Heath Ledger won a posthumous Academy Award for his role as the Joker in 'The Dark Knight'.", "correct_answer": "True"},
    {"question": "The movie 'Inception' deals with the concept of entering people's dreams.", "correct_answer": "True"},
    {"question": "'Mad Max: Fury Road' was released in the 1990s.", "correct_answer": "False"},
    {"question": "The sitcom 'The Big Bang Theory' revolves around a group of friends living in New York.", "correct_answer": "False"},
    {"question": "In 'Star Wars', the character who famously says 'I've got a bad feeling about this' in every episode is Han Solo.", "correct_answer": "False"},
    {"question": "The TV show 'F.R.I.E.N.D.S' had 12 seasons.", "correct_answer": "False"},
    {"question": "'Frozen' is a movie produced by DreamWorks.", "correct_answer": "False"},
    {"question": "'Westworld' is a TV series based on a novel written by Michael Crichton.", "correct_answer": "True"},
    {"question": "'Wakanda' is the fictional African nation in 'The Lion King'.", "correct_answer": "False"},
    {"question": "'Scarface' is a movie about a gangster in the 1920s during the prohibition era.", "correct_answer": "False"},
    {"question": "'The Office' is a mockumentary sitcom that depicts the everyday work lives of office employees.", "correct_answer": "True"},
    {"question": "'Avatar: The Last Airbender' is a TV series that aired on HBO.", "correct_answer": "False"},
    {"question": "'Grey's Anatomy' is a medical drama TV series.", "correct_answer": "True"},
    {"question": "'The Godfather' is a movie directed by Quentin Tarantino.", "correct_answer": "False"},
    {"question": "The movie 'Titanic' was released in 1999.", "correct_answer": "False"},
    {"question": "'Pulp Fiction' is known for its chronological story-telling.", "correct_answer": "False"},
    {"question": "'Chernobyl' is a historical drama TV series that revolves around the nuclear disaster of 1986.", "correct_answer": "True"},
    {"question": "The movie 'Toy Story' was produced by Pixar Animation Studios.", "correct_answer": "True"},
    {"question": "The movie 'La La Land' won the Academy Award for Best Picture in 2017.", "correct_answer": "False"},
    {"question": "Anthony Hopkins played the character of Hannibal Lecter in 'The Silence of the Lambs'.", "correct_answer": "True"},
    {"question": "The 'Rocky' film series primarily focuses on boxing.", "correct_answer": "True"},
    {"question": "'Django Unchained' is set during the times of the American Civil War.", "correct_answer": "True"},
    {"question": "The TV series 'Peaky Blinders' is set during the early 1900s in Birmingham, England.", "correct_answer": "True"},
    {"question": "'Parasite' is a South Korean black comedy thriller film directed by Bong Joon-ho.", "correct_answer": "True"},
    {"question": "In 'The Matrix', the main protagonist's hacker alias is Neo.", "correct_answer": "True"},
    {"question": "'Iron Man' was the first movie released in the Marvel Cinematic Universe.", "correct_answer": "True"},
    {"question": "The movie 'The Shawshank Redemption' is based on a novel written by Stephen King.", "correct_answer": "True"},
    {"question": "'Narcos' is a TV series that chronicles the life of drug lord Pablo Escobar.", "correct_answer": "True"},
    {"question": "In 'Game of Thrones', Daenerys Targaryen has two dragons.", "correct_answer": "False"},
    {"question": "'Black Mirror' is a TV series that explores a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.", "correct_answer": "True"},
    {"question": "'Breaking Bad' is a TV series that chronicles the life of a high school chemistry teacher turned methamphetamine manufacturer.", "correct_answer": "True"},
    {"question": "The movie 'A Beautiful Mind' is based on the life of mathematician John Nash.", "correct_answer": "True"},
    {"question": "The 'Harry Potter' film series consists of 8 movies.", "correct_answer": "True"},
    {"question": "'The Walking Dead' is a TV series that revolves around a group of survivors in a post-apocalyptic world filled with zombies.", "correct_answer": "True"},
    {"question": "The movie 'Forrest Gump' chronicles the life of a man with low intelligence and his adventures through the late 20th century.", "correct_answer": "True"},
    {"question": "In 'The Simpsons', the head of the Simpson family is named Homer.", "correct_answer": "True"},
    {"question": "'BoJack Horseman' is an animated TV series that revolves around a washed-up actor who is a horse and his struggles with addiction, self-worth, and relationships.", "correct_answer": "True"},
    {"question": "'Better Call Saul' is a prequel to 'Breaking Bad'.", "correct_answer": "True"},
    {"question": "The movie 'The Wolf of Wall Street' is based on the life of stockbroker Jordan Belfort.", "correct_answer": "True"},
    {"question": "The TV series 'Vikings' chronicles the legendary Norse hero Ragnar Lothbrok's journey as a legendary Norse hero and legendary king of Denmark.", "correct_answer": "True"},
    {"question": "The movie 'Casablanca' ends with the line 'Here's looking at you, kid.'", "correct_answer": "False"},
    {"question": "'Mufasa' is the main antagonist in 'The Lion King'.", "correct_answer": "False"},
    {"question": "'House of Cards' is a political drama series.", "correct_answer": "True"},
    {"question": "The movie 'The Shining' is based on a novel by Agatha Christie.", "correct_answer": "False"},
    {"question": "'Friends' and 'How I Met Your Mother' were created by the same person.", "correct_answer": "False"},
    {"question": "'Schindler's List' is a film directed by Martin Scorsese.", "correct_answer": "False"},
    {"question": "The character 'Michael Scott' is from the TV series 'Parks and Recreation'.", "correct_answer": "False"},
    {"question": "'R2-D2' is a character from the 'Star Trek' series.", "correct_answer": "False"},
    {"question": "The movie 'Psycho' was directed by Alfred Hitchcock.", "correct_answer": "True"},
    {"question": "The 'Fast & Furious' movie series primarily focuses on heists and street racing.", "correct_answer": "True"},
    {"question": "The TV show 'Sherlock' features Benedict Cumberbatch as Dr. John Watson.", "correct_answer": "False"},
    {"question": "'James Bond' is a character created by author Ian Fleming.", "correct_answer": "True"},
    {"question": "The film 'Interstellar' was directed by Christopher Nolan.", "correct_answer": "True"},
    {"question": "'The Good Place' is a TV series that revolves around the afterlife and moral philosophy.", "correct_answer": "True"},
    {"question": "The movie 'Fight Club' was based on a novel by Chuck Palahniuk.", "correct_answer": "True"},
    {"question": "'Dexter' is a TV series about a forensic expert who leads a secret life as a serial killer.", "correct_answer": "True"},
    {"question": "The movie 'Braveheart' depicts the life of William Wallace, a Scottish warrior.", "correct_answer": "True"},
    {"question": "'Modern Family' is a TV show presented in a mockumentary style.", "correct_answer": "True"},
    {"question": "'Avatar' directed by James Cameron is the highest grossing film of all time as of 2021.", "correct_answer": "False"},
    {"question": "The film 'Coco' revolves around the Mexican holiday 'Day of the Dead'.", "correct_answer": "True"},
    {"question": "'Al Pacino' played the character Michael Corleone in 'The Godfather'.", "correct_answer": "True"},
    {"question": "'Doctor Who' is a long-running British science-fiction television series.", "correct_answer": "True"},
    {"question": "The character 'Indiana Jones' is an archaeologist.", "correct_answer": "True"},
    {"question": "'Fargo' is both a film and a TV series.", "correct_answer": "True"},
    {"question": "The movie 'A Clockwork Orange' was directed by Stanley Kubrick.", "correct_answer": "True"},
    {"question": "The film 'Finding Nemo' is about a young fish trying to find his lost father.", "correct_answer": "False"},
    {"question": "'Marty McFly' is a character from the 'Back to the Future' series.", "correct_answer": "True"},
    {"question": "The TV series 'Lost' is about survivors of a plane crash stranded on a mysterious island.", "correct_answer": "True"},
    {"question": "'Hannibal' is a TV series that revolves around FBI profiler Will Graham and his relationship with Dr. Hannibal Lecter.", "correct_answer": "True"},
    {"question": "The film 'Blade Runner' is based on a novel by Philip K. Dick.", "correct_answer": "True"},
    {"question": "'Arrested Development' is a TV series that follows the dysfunctional Bluth family.", "correct_answer": "True"},
    {"question": "'12 Angry Men' is a film about a jury deliberating the guilt of a defendant.", "correct_answer": "True"},
    {"question": "The movie 'The Sound of Music' is set during World War I.", "correct_answer": "False"},
    {"question": "'The X-Files' is a TV series that revolves around two FBI agents investigating unsolved and often inexplicable cases.", "correct_answer": "True"},
    {"question": "The movie 'Dead Poets Society' stars Robin Williams as an English teacher.", "correct_answer": "True"},
    {"question": "The film 'E.T. the Extra-Terrestrial' is about a young boy's friendship with an alien.", "correct_answer": "True"},
    {"question": "'Daredevil', 'Jessica Jones', and 'Luke Cage' are TV series that are part of the Marvel Cinematic Universe.", "correct_answer": "True"},
    {"question": "The film 'The Sixth Sense' was directed by M. Night Shyamalan.", "correct_answer": "True"},
    {"question": "The character 'Wolverine' is played by Hugh Jackman in the 'X-Men' film series.", "correct_answer": "True"},
    {"question": "'True Detective' is an anthology crime drama TV series.", "correct_answer": "True"},
    {"question": "The movie 'A Star is Born' has only been made once in Hollywood history.", "correct_answer": "False"},
    {"question": "'Twin Peaks' is a TV series created by David Lynch.", "correct_answer": "True"},
    {"question": "The character 'John Wick' is portrayed by Keanu Reeves.", "correct_answer": "True"},
    {"question": "'The Sopranos' is a TV series about a mob boss seeking therapy for his personal and professional troubles.", "correct_answer": "True"},
    {"question": "'The Usual Suspects' features a mysterious character named Keyser Söze.", "correct_answer": "True"},
    {"question": "'M*A*S*H' is a TV series set during the Vietnam War.", "correct_answer": "False"},
    {"question": "'The Princess Bride' is a film that combines elements of comedy, adventure, and romance.", "correct_answer": "True"},
    {"question": "'Suits' is a TV series that follows the lives of lawyers at a fictional New York City law firm.", "correct_answer": "True"},
    {"question": "The movie 'Casino Royale' introduced Daniel Craig as James Bond.", "correct_answer": "True"},
    {"question": "'American Psycho' is a film about a Wall Street banker who leads a secret life as a serial killer.", "correct_answer": "True"},
    {"question": "The movie 'No Country for Old Men' was directed by the Coen Brothers.", "correct_answer": "True"},
    {"question": "The character 'Sheldon Cooper' is from the TV series 'How I Met Your Mother'.", "correct_answer": "False"},
    {"question": "'Moonlight' won the Academy Award for Best Picture in 2016.", "correct_answer": "True"},
    {"question": "The movie 'Gladiator' stars Russell Crowe as a Roman general seeking vengeance.", "correct_answer": "True"},
    {"question": "'The Wire' is a TV series that offers a detailed exploration of the city of Baltimore.", "correct_answer": "True"},
    {"question": "'Birdman' is a film that appears as if it was shot in a single continuous take.", "correct_answer": "True"},
    {"question": "'Orange Is the New Black' is a TV series set in a women's prison.", "correct_answer": "True"},
    {"question": "The movie 'Goodfellas' is based on a book by Nicholas Pileggi.", "correct_answer": "True"},
    {"question": "The character 'Michael Corleone' is the protagonist of 'The Sopranos'.", "correct_answer": "False"},
    {"question": "'Once Upon a Time in Hollywood' is a film directed by Quentin Tarantino.", "correct_answer": "True"},
    {"question": "'Fleabag' is a British comedy-drama TV series created and written by Phoebe Waller-Bridge.", "correct_answer": "True"},
    {"question": "The movie 'Gone Girl' is based on a novel by the same name written by Gillian Flynn.", "correct_answer": "True"},
    {"question": "'Downton Abbey' is a TV series that chronicles the lives of the British aristocratic Crawley family.", "correct_answer": "True"},
    {"question": "The film 'Requiem for a Dream' was directed by Darren Aronofsky.", "correct_answer": "True"},
    {"question": "The movie 'The Departed' is a remake of a Hong Kong film called 'Infernal Affairs'.", "correct_answer": "True"},
    {"question": "'Mad Men' is a TV series set in the 1960s at an advertising agency in New York City.", "correct_answer": "True"},
    {"question": "The movie 'Whiplash' is about a young drummer and his demanding music instructor.", "correct_answer": "True"},
    {"question": "'Curb Your Enthusiasm' is a TV show created by and starring Larry David playing a fictionalized version of himself.", "correct_answer": "True"},
    {"question": "The film 'Blade Runner 2049' was directed by Ridley Scott.", "correct_answer": "False"},
    {"question": "'Ozark' is a TV series about a financial planner who relocates his family to the Ozarks after a money-laundering scheme goes wrong.", "correct_answer": "True"},
    {"question": "The movie 'There Will Be Blood' stars Daniel Day-Lewis as an oilman.", "correct_answer": "True"},
    {"question": "'Brooklyn Nine-Nine' is a comedic TV series set in a New York City police department.", "correct_answer": "True"},
    {"question": "'The Grand Budapest Hotel' is a film directed by Wes Anderson.", "correct_answer": "True"},
    {"question": "'Killing Eve' is a TV series that focuses on the cat-and-mouse game between an intelligence investigator and an assassin.", "correct_answer": "True"},
    {"question": "'Her' is a film about a man who develops a relationship with an intelligent computer operating system.", "correct_answer": "True"},
    {"question": "The movie 'The Social Network' chronicles the creation of Twitter.", "correct_answer": "False"},
    {"question": "'True Blood' is a TV series about a small town in Louisiana where vampires live openly with humans.", "correct_answer": "True"},
    {"question": "The film 'The Big Lebowski' centers around a character named Jeff 'The Dude' Lebowski.", "correct_answer": "True"},
    {"question": "'Veep' is a political satire TV series starring Julia Louis-Dreyfus.", "correct_answer": "True"},
    {"question": "The movie 'Memento' is presented in a non-linear narrative.", "correct_answer": "True"},
    {"question": "'Breaking Bad' was followed by a sequel film named 'El Camino'.", "correct_answer": "True"},
    {"question": "The movie 'Black Swan' is centered around the world of professional ballet.", "correct_answer": "True"},
]