#pop_culture_questions.py
question_data = [
    {"question": "Beyoncé was a member of the group Destiny's Child.", "correct_answer": "True"},
    {"question": "The Beatles were formed in Manchester.", "correct_answer": "False"},
    {"question": "'Despacito' is a hit song by Ed Sheeran.", "correct_answer": "False"},
    {"question": "Lady Gaga's real name is Stefani Joanne Angelina Germanotta.", "correct_answer": "True"},
    {"question": "Ariana Grande began her career on the TV show 'Victorious'.", "correct_answer": "True"},
    {"question": "The TV show 'Keeping Up with the Kardashians' began airing in 2010.", "correct_answer": "False"},
    {"question": "Rihanna is originally from Barbados.", "correct_answer": "True"},
    {"question": "The 'Mona Lisa' is housed in the Louvre Museum in Paris.", "correct_answer": "True"},
    {"question": "Marilyn Monroe starred in the movie 'Gone with the Wind'.", "correct_answer": "False"},
    {"question": "Billie Eilish's debut album is titled 'Bad Guy'.", "correct_answer": "False"},
    {"question": "The character Jack Dawson, from the movie 'Titanic', is played by Brad Pitt.", "correct_answer": "False"},
    {"question": "The song 'Shape of You' is sung by Justin Bieber.", "correct_answer": "False"},
    {"question": "Taylor Swift's album '1989' was released in the year 1989.", "correct_answer": "False"},
    {"question": "The character 'Spider-Man' was first introduced by Marvel Comics in the 1960s.", "correct_answer": "True"},
    {"question": "The novel 'Fifty Shades of Grey' was written by J.K. Rowling.", "correct_answer": "False"},
    {"question": "'WAP' is a hit song by Megan Thee Stallion and Cardi B.", "correct_answer": "True"},
    {"question": "The 'Floss' dance move became popular because of the video game Fortnite.", "correct_answer": "True"},
    {"question": "Kanye West's album 'Graduation' was released after 'My Beautiful Dark Twisted Fantasy'.", "correct_answer": "False"},
    {"question": "The movie 'The Social Network' is based on the creation of Twitter.", "correct_answer": "False"},
    {"question": "Elon Musk is the founder of Amazon.", "correct_answer": "False"},
    {"question": "Oprah Winfrey ran for the U.S. presidency in 2016.", "correct_answer": "False"},
    {"question": "'Stranger Things' is set in the fictional town of Hawkins.", "correct_answer": "True"},
    {"question": "The character 'Wonder Woman' hails from the island of Themyscira.", "correct_answer": "True"},
    {"question": "The 'Macarena' dance originated in the 2010s.", "correct_answer": "False"},
    {"question": "Michael Jackson is known as the 'King of Rock'.", "correct_answer": "False"},
    {"question": "The 2020s viral dance trend 'Renegade' originated on TikTok.", "correct_answer": "True"},
    {"question": "Dua Lipa's song 'Don't Start Now' is from her debut album.", "correct_answer": "False"},
    {"question": "'Baby Yoda' is the official name of the character from 'The Mandalorian'.", "correct_answer": "False"},
    {"question": "The TV show 'Game of Thrones' is based on the book series 'A Song of Ice and Fire'.", "correct_answer": "True"},
    {"question": "The 'Dab' dance move was popularized by the singer Rihanna.", "correct_answer": "False"},
    {"question": "The character 'Iron Man' is also known as Steve Rogers.", "correct_answer": "False"},
    {"question": "The artist who sang 'Rolling in the Deep' is Adele.", "correct_answer": "True"},
    {"question": "The TV show 'Breaking Bad' is set in the city of Albuquerque.", "correct_answer": "True"},
    {"question": "Jennifer Aniston played the character of Monica in the TV show 'F.R.I.E.N.D.S'.", "correct_answer": "False"},
    {"question": "The song 'Old Town Road' is by Lil Nas X.", "correct_answer": "True"},
    {"question": "The 'Ice Bucket Challenge' was a viral trend in 2019.", "correct_answer": "False"},
    {"question": "The first iPhone was released in 2005.", "correct_answer": "False"},
    {"question": "Billie Eilish's brother, Finneas, is also her musical collaborator.", "correct_answer": "True"},
    {"question": "Kendall Jenner is the eldest of the Jenner/Kardashian siblings.", "correct_answer": "False"},
    {"question": "The movie 'La La Land' stars Emma Stone and Ryan Reynolds.", "correct_answer": "False"},
    {"question": "Britney Spears' debut single was 'Oops!... I Did It Again'.", "correct_answer": "False"},
    {"question": "The video game 'Among Us' was released in 2020.", "correct_answer": "False"},
    {"question": "The novel 'The Great Gatsby' was written by Ernest Hemingway.", "correct_answer": "False"},
    {"question": "Kobe Bryant played for the Los Angeles Lakers.", "correct_answer": "True"},
    {"question": "The song 'Hotline Bling' is by Kendrick Lamar.", "correct_answer": "False"},
    {"question": "The 2010s dance trend 'Gangnam Style' originated in China.", "correct_answer": "False"},
    {"question": "Tom Holland has portrayed the character 'Spider-Man' in the Marvel Cinematic Universe.", "correct_answer": "True"},
    {"question": "The animated film 'Shrek' was released in the 1990s.", "correct_answer": "False"},
    {"question": "The singer known as the 'Material Girl' is Madonna.", "correct_answer": "True"},
    {"question": "The 2020 Netflix documentary 'Tiger King' focuses on the life of Joe Biden.", "correct_answer": "False"}
]
