#sports_questions.py
question_data = [
    {"question": "The Olympics are held every five years.", "correct_answer": "False"},
    {"question": "In tennis, a 'love' means the player has zero points.", "correct_answer": "True"},
    {"question": "A basketball team has 6 players on the court at any given time.", "correct_answer": "False"},
    {"question": "Pele is a famous name associated with football.", "correct_answer": "True"},
    {"question": "The term 'birdie' is associated with golf.", "correct_answer": "True"},
    {"question": "Boxing matches have 11 rounds.", "correct_answer": "False"},
    {"question": "Formula 1 racing originated in Britain.", "correct_answer": "True"},
    {"question": "In baseball, the pitcher stands on the mound.", "correct_answer": "True"},
    {"question": "The duration of a rugby match is 60 minutes.", "correct_answer": "False"},
    {"question": "Volleyball was invented as a game for businessmen.", "correct_answer": "False"},
    {"question": "Michael Phelps has won 23 gold medals in the Olympics.", "correct_answer": "True"},
    {"question": "Cricket has 9 players in one team.", "correct_answer": "False"},
    {"question": "The FIFA World Cup is held every 3 years.", "correct_answer": "False"},
    {"question": "A chessboard has 48 squares.", "correct_answer": "False"},
    {"question": "The term 'slam dunk' is used in basketball.", "correct_answer": "True"},
    {"question": "Roger Federer is a famous name in the world of badminton.", "correct_answer": "False"},
    {"question": "The first modern Olympics took place in 1896.", "correct_answer": "True"},
    {"question": "Lionel Messi is known for playing tennis.", "correct_answer": "False"},
    {"question": "A marathon is a race of approximately 42.2 kilometers.", "correct_answer": "True"},
    {"question": "Archery is the sport of shooting arrows with a crossbow.", "correct_answer": "False"},
    {"question": "A football (soccer) match consists of two periods of 45 minutes each.", "correct_answer": "True"},
    {"question": "The Super Bowl is the final championship of NBA.", "correct_answer": "False"},
    {"question": "In 2021, the Olympics were held in Tokyo.", "correct_answer": "True"},
    {"question": "The Tour de France is an annual men's multiple stage bicycle race primarily held in Italy.", "correct_answer": "False"},
    {"question": "The 'Ashes' is a test cricket series played between England and Australia.", "correct_answer": "True"},
    {"question": "Wimbledon is a Grand Slam tennis tournament that is played on clay.", "correct_answer": "False"},
    {"question": "Muhammad Ali was a famous basketball player.", "correct_answer": "False"},
    {"question": "A football field is also called a 'pitch'.", "correct_answer": "True"},
    {"question": "The game of basketball was invented by Dr. James Naismith.", "correct_answer": "True"},
    {"question": "In ice hockey, the team's goal scorer is also called a 'quarterback'.", "correct_answer": "False"},
    {"question": "The Summer Olympics include the sport of skeleton racing.", "correct_answer": "False"},
    {"question": "The Ryder Cup is associated with golf.", "correct_answer": "True"},
    {"question": "A 'scrum' is a term used in rugby.", "correct_answer": "True"},
    {"question": "The term 'hat trick' originated from cricket.", "correct_answer": "True"},
    {"question": "The sport of 'fencing' involves fighting with swords.", "correct_answer": "True"},
    {"question": "Michael Jordan played major league baseball.", "correct_answer": "True"},
    {"question": "The Grand Slam tournaments are the most important events in professional tennis.", "correct_answer": "True"},
    {"question": "In basketball, a player can score a maximum of three points from a shot made outside the three-point line.", "correct_answer": "True"},
    {"question": "A 'bunker' is a term used in golf.", "correct_answer": "True"},
    {"question": "A 'googly' is a type of shot in basketball.", "correct_answer": "False"},
    {"question": "The 'Heisman Trophy' is awarded in the sport of baseball.", "correct_answer": "False"},
    {"question": "The term 'stumped' is used in cricket.", "correct_answer": "True"},
    {"question": "The maximum number of players allowed on the field in American football is 11.", "correct_answer": "True"},
    {"question": "The sport which is known as 'the king of sports' is horse racing.", "correct_answer": "True"},
    {"question": "The 'World Series' is associated with baseball.", "correct_answer": "True"},
    {"question": "FIFA is the international governing body of cricket.", "correct_answer": "False"},
    {"question": "A standard Olympic-sized swimming pool is 50 meters long.", "correct_answer": "True"},
    {"question": "Billiards and snooker are the same sport.", "correct_answer": "False"},
    {"question": "A 'knockout' term is used in professional boxing when a fighter cannot continue after a 10-count.", "correct_answer": "True"},
    {"question": "The 'Indy 500' is a car race that is held annually in France.", "correct_answer": "False"}
]
